version: '3'
services:
    polite:
        build: ./politeService
        ports:
            - 3001:3000
        volumes:
            - ./politeService:/usr/src/app
        command: ["npm", "run","watch"]
    users:
        build: ./userService
        ports:
            - 3002:3000
        volumes:
            - ./userService:/usr/src/app
        command: ["npm", "run","watch"]

