version: '3'
services:
    polite:
        build: 
            context: ./politeService
            args:
                PORT: 8080
        ports:
            - 3001:8080
        command: ["npm", "start"]
    users:
        build: 
            context: ./userService
            args:
                PORT: 8080
        ports:
            - 3002:8080
        command: ["npm", "start"]
    mainapp:
        environment:
            POLITE_SERVICE_URL: 'http://polite:8080/'
            USERS_SERVICE_URL: 'http://users:8080/'
        build: 
            context: ./mainApp
            args:
                PORT: 8080
        depends_on:
            - polite
            - users
        ports:
            - 3003:8080
        command: ["npm", "start"]

