version: '3'
services:
    polite:
        build: ./politeService
        ports:
            - 3001:3000
        volumes:
            - ./politeService:/usr/src/app
        command: ["npm", "run","watch"]
    users:
        build: ./userService
        ports:
            - 3002:3000
        volumes:
            - ./userService:/usr/src/app
        command: ["npm", "run","watch"]
    mainapp:
        environment:
            POLITE_SERVICE_URL: 'http://polite:3000/'
            USERS_SERVICE_URL: 'http://users:3000/'
        build: ./mainApp
        depends_on:
            - polite
            - users
        ports:
            - 3003:3000
        volumes:
            - ./mainApp:/usr/src/app
        command: ["npm", "run","watch"]

