apiVersion: v1
kind: Pod
metadata:
  name: politepod
  labels:
    env: dev
    creation_method: manual
spec:
  containers:
  - image: politecontainer
    name: kubia
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
        httpGet:
            path: /k8/hello
            port: 8080
